### ISSUE TITLE
Upgrade graphql-language-service-interface to 0.7.0

### ISSUE THREAD

**Issue by bakso** [graphql/codemirror-graphql#171]
0.4.0 is not the lastest version

**Comment by wincent** [comment]
Correct. It's not the latest version. Is there a specific bugfix from a later version that you depend on? (I'm not aware of any changes that would be relevant to `codemirror-graphql`, but I may have missed something.)

I think we can probably close this because we already have a couple of PRs from Greenkeeper (eg https://github.com/graphql/codemirror-graphql/pull/142 and https://github.com/graphql/codemirror-graphql/pull/145) for this; we just need to merge them.

**Comment by bakso** [comment]
Hurry hurry up!hahaaa

**Comment by wincent** [comment]
Closing. As per #175, we'll cut a release this week.
