### ISSUE TITLE
automatically fills in leaf nodes 

### ISSUE THREAD

**Issue by xinshangshangxin** [graphql/codemirror-graphql#232]
https://github.com/graphql/graphiql#usage-examples
```js
      // GraphiQL automatically fills in leaf nodes when the query
      // does not provide them. Change this if your GraphQL Definitions
      // should behave differently than what's defined here:
      // (https://github.com/graphql/graphiql/blob/master/src/utility/fillLeafs.js#L75)
      getDefaultFieldNames: null
```

when no query and press `cmd + enter`, automatically fills in leaf nodes  like GraphiQL

**Comment by xinshangshangxin** [comment]
@wincent

**Comment by wincent** [comment]
@xinshangshangxin: can you clarify the nature of this issue? I'm not sure if it is a question, a proposal or a bug report.

**Comment by xinshangshangxin** [comment]
it is a proposal.

When I write a query name, and no leaf nodes given,  Then press `cmd + enter`, it will fill the `leaf nodes` before send, like the gif

![graphiql](https://user-images.githubusercontent.com/8779091/29594972-243f8f50-87e7-11e7-87bb-d26eadde8166.gif)

**Comment by asiandrummer** [comment]
@xinshangshangxin It's still not really clear why you'd like this feature in this library. Since `codemirror-graphql` is just a set of wrappers for GraphQL language service, it's probably not appropriate for this library to contain the logic to auto-filling leaf nodes - that feature handles a very specific use case. OTOH I do see how the autofill feature could reside in the language service repo. I'd be open for a PR for that if you're down for it please.

[This code](https://github.com/graphql/graphiql/blob/master/src/utility/fillLeafs.js) handles the auto-filling of leaf nodes.

**Comment by asiandrummer** [comment]
I'm closing this issue since I still believe that feature does not belong in this library. Let me know if you think otherwise - I'd like to understand the reasoning behind it.

**Comment by xinshangshangxin** [comment]
thanks @asiandrummer
