### ISSUE TITLE
Export `mode` as its own package

### ISSUE THREAD

**Issue by mfix22** [graphql/codemirror-graphql#237]
We would like to consume just the GraphQL mode file. Would it be possible to release that as its own package?

**Comment by asiandrummer** [comment]
Hi @mfix22! Would it suffice to import `codemirror-graphql/mode`?

**Comment by mfix22** [comment]
Yeah I think so! We are going to use it in the browser (obviously) so we just want the import to be as small as possible.

Right now if we import `codemirror-graphql/mode` will only the one package get included? That might be out of the scope of this issue (:

**Comment by asiandrummer** [comment]
@mfix22 -
>  I would just like to import this function, the one passed to CodeMirror.defineMode

I take that you'd like to import the mode function, as well as the required imported modules that include `CodeMirror` and `graphql-language-service-parser`.
```
$ du -hcs node_modules/codemirror
3.2M	../codemirror
$ du -hcs node_modules/graphql-language-service-parser
 84K	../graphql-language-service-parser/
$ du -hcs node_modules/codemirror-graphql
116K	../codemirror-graphql
$ du -hcs node_modules/codemirror-graphql/mode.js
4.0K	../codemirror-graphql/mode.js
```
So if we just released, let's say `codemirror-graphql-mode` only, then we'd save around 100K (LICENSE/README/package.json takes up 12K in my calculation). Since in any case you'd have to import `CodeMirror` that is ~3200K already, I'd say you're not saving much.

I understand that I may not be familiar with your situation though - may I ask what your use case is? Is ~100K addition enough to hinder the performance in your web application? I'm willing to consider releasing said `codemirror-graphql-mode` if it's absolutely necessary under a good business use case. cc @wincent I'd like to get your input as well please!

**Comment by wincent** [comment]
It would be desirable to tackle this at the build stage, I think: if you directly require "codemirror-graphql/mode" (and only that), you would ideally be able to bundle only that and its dependencies (which as @asiandrummer points out, are quite large). If there is some technical obstacle to that in how codemirror-graphq is structured, we should fix it (although I am not aware of any issues), but I don't think creating a separate package should be necessary.

**Comment by mfix22** [comment]
Hey guys after further thought, I am going to close this. Every scenario where I would like to use that function is for `CodeMirror`-y things, in which case I will already have to import CodeMirror. Thanks for the discussion!
